image: ruby:latest
cache:
  paths:
  - .bundle
before_script:
- gem install bundler:2.0.1
- bundle --path .bundle/gems
pages:
  script:
  - bundle exec jekyll build -d public --config _config.yml,_config-gitlab.yml -q
  artifacts:
    paths:
    - public
  only:
  - master
