= De zwartepietdialoog

[.lead]
Hij is er weer: de inmiddels traditionele, jaarlijks terugkerende, oer-Hollandse zwartepietdiscussie. Zouden we daar een constructieve dialoog van kunnen maken?

Oorspronkelijk bestond de zwartepietdiscussie uit twee meningen:

1. Zwarte Piet moet blijven zoals het was. Handen af van ons Sinterklaasfeest!
2. Zwarte Piet is racistisch en niet meer van deze tijd. Weg met Zwarte Piet!

Inmiddels is daar ook een derde mening bijgekomen:

[start=3]
3. Pfff, alwéér deze discussie? Stop hier nou eens mee!

Wat gebeurt er in een discussie? De partijen gaan fel tegen elkaar in, en de een probeert de ander te overtuigen van het eigen gelijk.

En wat gebeurt er _niet_? Gek genoeg wordt er niet of nauwelijks geluisterd naar wat de ander zegt.

Want wat zegt iemand die Zwarte Piet wil houden zoals het was? Diegene wil een leuk feestje, en denkt dat het feestje minder leuk wordt als Zwarte Piet er anders uitziet dan vroeger.

En wat zegt iemand die Zwarte Piet weg wil hebben? Diegene wil een leuk feestje, en denkt dat het feestje leuker is als Piet niet meer Zwart is.

En wat zegt iemand die moe wordt van de hele discussie? Diegene wil een leuk feestje, en denkt dat de discussie over Zwarte Piet het feestje verpest.

Wie heeft gelijk? Iedereen! En niemand!

Iedereen denkt zijn of haar eigen gedachten, en in zijn of haar wereld is dat waar. En dus heeft tegelijkertijd ook niemand gelijk, want er is geen gelijk te halen. Het is simpelweg ieders eigen waarheid. We kunnen proberen de ander op andere gedachten te brengen, maar dat is uiteindelijk een heilloze weg.

In plaats daarvan kunnen we dat ook _niet_ doen, en simpelweg naar de ander luisteren. En als je dat doet, in dit geval door hierboven nogmaals te lezen wat alledrie de partijen zeggen, zie je dat er onder elk denkbeeld dezelfde behoefte zit: een leuk feestje.

De denkbeelden over hoe dat feestje eruit zou moeten zien, hoe echt ze ook kunnen lijken, leiden af en verpesten datzelfde leuke feestje. Het onderliggende besef dat iedereen – echt iedereen – uiteindelijk een leuk feestje wil, geeft rust, en maakt dat feestje mogelijk.

Laten we daarom vanuit die rust naar de ander luisteren, en daarna tegen de ander zeggen "ik begrijp dat je er zo over denkt". Als we dat wederzijds doen, dan hebben we geen discussie meer, maar een dialoog.

Dat wordt dan onze jaarlijkse zwartepietdialoog – een nieuwe oer-Hollandse traditie van begripvol naar elkaars gedachtenwereld luisteren, in het vertrouwen dat we uiteindelijk allemaal hetzelfde zijn.
