= Auto's op de snelweg

[.lead]
Soms zijn er dingen die zo ineens opkomen.

Althans, ik zeg nu "soms", maar eigenlijk is dat "de hele dag door".

Dus even opnieuw:

De hele dag door zijn er dingen die zo ineens opkomen.

Laatst was ik in gesprek met iemand terwijl we uitzicht hadden over een snelweg. De langsrijdende auto's op de weg werden een metafoor voor "dingen die de hele dag door opkomen".

Dat ging ongeveer als volgt.

Je kunt uit het verkeer één auto kiezen en die heel nauwkeurig gaan volgen:

* Hoe hard rijdt de auto?
* Gaat hij inhalen?
* Waar komt hij vandaan?
* Welke afslag gaat hij nemen?
* Wat zou hij vervoeren?
* Hoe zou de bestuurder eruit zien?
* Is de kleur nou lichtgroen of meer een soort van mosterdgeel?

In een paar tellen is een heel verhaal ontstaan rondom die ene auto. Die ene auto lijkt voor even het centrum van het universum.

En dat is best fascinerend! Het was namelijk totaal willekeurig wélke auto je besloot te gaan volgen.

Tot zover de auto's, want waarvoor zijn die dan een metafoor? Bijvoorbeeld:

* Een idee voor een nieuw bedrijf
* Een herinnering aan iemand die net overleden is
* Een gevoel van honger
* Een rekening die je nog moet betalen
* Een grap in een film die je vorige week hebt gekeken

Zomaar een greep uit de vele, vele dingen die langskomen op de snelweg des levensfootnote:[Goh, "snelweg des levens", hoe kóm ik erop! Walgelijk. En sorry.].

Als zoiets langskomt plakken we daar vrijwel direct etiketten op als "leuk", "saai", "verdrietig", of "stom".

En daar vinden we dan ook weer wat van, want "saai" en "stom" willen we niet en "leuk" daar willen we meer van.

Vervolgens gaan we dan bedenken wat we allemaal kunnen doen om minder "saai" en meer "leuk" in ons leven te krijgen.

Etcetera.

Terwijl het allemaal maar gewoon auto's zijn die langsrijden op de snelweg.

En om nou over elke auto te gaan bedenken wat je ervan vindt…

"Pfffff" is wat opkomt als ik daar aan denk.

Al is dat natuurlijk vrij willekeurig.
