= Je weet het niet

[.lead]
Soms denk je van tevoren te weten hoe iets zal gaan. Maar eigenlijk weet je het niet.

Tijdens de zwangerschap van ons derde kind reageerden dochter (6) en zoon (4) allebei op hun eigen manier op de baby in de buik.

Dochter vond het toen ze het hoorde heel leuk dat ze een zusje kreeg. Ze vond de baby in de buik ook wel interessant. De zwangerschap leek alleen niet per se meer of minder interessant dan andere dingen die gebeurden.

Zoon was juist heel erg specifiek geïnteresseerd in de baby en de buik. Hij ging praten tegen de buik en er kusjes op geven. De baby was zo’n beetje hét onderwerp voor hem de gedurende de zwangerschap.

Echtgenote en ik dachten: nou, dat is dus duidelijk. Als straks de baby er is, dan zul je zien dat dochter er niet veel naar omkijkt – want dat deed ze toch ook al niet echt toen haar broertje nog baby was – en dat zoon helemaal los gaat en kleertjes gaat uitzoeken, luiers helpt verschonen en de hele dag wil knuffelen met de baby.

De praktijk wees anders uit. Dochter ontpopte zich al snel tot een tweede moeder voor de baby en zoon leek dusdanig overweldigd door de komst van het nieuwe gezinslid dat hij zich de eerste dagen niet zo goed raad wist met wat te doen.

Ha, daar dachten wij toch mooi even de toekomst te kunnen voorspellen! In dit geval hadden we het mis. Maar al we hadden we het goed voorspeld, dan nog weet je dat van tevoren niet zeker.

Die collega die de vorige keer zo chagrijnig reageerde toen je iets vroeg? Hij zou deze keer weer bits kunnen reageren, maar je weet het niet.

Je kind dat vorige keer zoveel water morste toen ze zelf haar glas ging bijvullen? Dat zou nu weer kunnen gebeuren, maar je weet het niet.

Viel het tegen toen je de vorige keer van baan wisselde? Dat zou nu weer kunnen gebeuren, maar je weet het niet.

Je kunt eigenlijk maar één ding zeggen over wat in de toekomst gaat gebeuren: je weet het niet.

En dat weet je dan nu weer wél.

Of niet?
