= Drukte om niks

[.lead]
Een gezin met jonge kinderen, een uitdagende baan en ook nog je relatie leuk houden: best hectisch, niet?

Kinderen gaan naar school, sport en hobby’s, op je werk is het leuk, maar soms ook druk en hectisch, en tussendoor belt je partner ook nog onverwacht met een dringende vraag. Je zou er zomaar stress van kunnen krijgen of het als druk kunnen ervaren.

Laten we daar eens wat dieper op ingaan.

Want wat betekenen druk en stress eigenlijk? De begrippen lijken sterk op elkaar. Druk ervaar je als meer van je gevraagd wordt dan je denkt aan te kunnen. En stress kun je zien als een verschil tussen wat je wil en wat je kan.

Wat is dan precies “wat je wil”? Kennelijk is er een idee over hoe “het” moet zijn – een banksaldo, een huis, een baan, noem het maar op. En stress ontstaat dan kennelijk als “het” in werkelijkheid niet overeenkomt met dat idee.

Zo’n idee is een illusie. Best geestig eigenlijk. Eerst komt een op zichzelf vrij willekeurig idee (een illusie!) op van hoe iets hoort te zijn en daarna is er boosheid, spanning, angst, onzekerheid omdat nergens dat idee weerspiegeld wordt in de waargenomen realiteit.

Wat nou als we die illusie als neutraal beschouwen? Simpelweg een idee van hoe iets zou kunnen zijn, zonder oordeel of dat goed of fout is, gewenst of ongewenst, heel erg of juist heel leuk. En zonder het tot een norm te verheffen waaraan de werkelijkheid moet voldoen.

Maakt het dan nog uit hoeveel er gebeurt? Dat er én iets gebeurt met de kinderen én met je partner én op het werk, allemaal op dezelfde dag? Waar blijft dan die stress en die druk? Of was dat stiekem misschien drukte om niks?
