= Voor de vorm

[.lead]
Tijdens de zwangerschap ben ik een aantal keer meegegaan naar afspraken. Meestal bij de verloskundige, soms in het ziekenhuis. Het viel me op hoe verschillend deze ervaringen waren.

Bij de balie in het ziekenhuis werd eerst om achternaam en geboortedatum gevraagd. Niet heel gek bij een eerste afspraak, maar ook bij vervolgafspraken bleef dit zo.

Vervolgens was het een kwestie van wachten op een bankje in een gang. Artsen en verpleegkundigen liepen in en uit, maar ze leken de wachtende mensen niet echt te zien en je kon niet weten wie precies wie was en wanneer je aan de beurt zou zijn.

Eenmaal aan de beurt kwamen we bij een verpleegkundige. Zij nam de bloeddruk op en stelde een aantal vragen. Dit waren hele basale vragen, waarop de antwoorden grotendeels al bekend waren. De verloskundige had van tevoren immers alle medische gegevens digitaal naar het ziekenhuis doorgestuurd. Toen ik dat navroeg was het antwoord “Ja dat klopt, maar dit zijn gewoon de standaardvragen die we altijd stellen”.

Daarna zaten we bij de arts. Dit was een kort gesprek, waarbij de arts de conclusies ondertussen meteen uittypte. De arts verwees ons terug naar de verpleegkundige om een vervolgafspraak te plannen. Toen deze geen geschikt tijdstip kon vinden, ging ze in overleg met de arts, die bij nader inzien een arts-assistent bleek te zijn, en daarom zelf ook weer met de eindverantwoordelijke arts moest overleggen om te bepalen wat dan de te kiezen aanpak moet zijn.

Al met al waren we bijna drie kwartier in het ziekenhuis voor nog geen drie minuten gesprek met een arts.

Dat was nogal een contrast met de ervaringen bij de verloskundige. De verloskundige werkt in een kleine praktijk met één wachtruimte, één bureau voor de praktijkassistent en één behandelkamer. Je naam en geboortedatum hoef je niet meer te noemen na de eerste afspraak. Ook de verhouding tussen wachttijd en gesprekstijd is heel anders dan in het ziekenhuis.

Maar veel is ook hetzelfde. De bloeddruk wordt gemeten, de assistent stelt administratieve vragen en de verloskundige registreert tijdens het gesprek informatie in een computersysteem.

Wat maakt dan uiteindelijk het verschil?

Ik zou nu een heel pleidooi kunnen houden voor kleinschaligheid in de zorg. Minder overhead, meer handen aan het bed, de menselijke maat, etcetera. Ik zou hetzelfde kunnen doen voor het onderwijs of voor het bedrijfsleven: al die regels en procedures, managementlagen en methoden, laten we terug naar de basis en in kleinere organisaties gaan werken waar we elkaar persoonlijk kennen.

Een aantrekkelijk verhaal misschien, maar het mist de kern. De ene vorm (kleinschalig en persoonlijk) boven de andere (grootschalig en onpersoonlijk) verheffen is te makkelijk. Een vierkoppige rockband is niet beter dan een symfonieorkest met honderd mensen – heel anders, dat zeker, maar beter of slechter is niet eenduidig te zeggen. Ook in grote orkesten, ziekenhuizen, scholen en bedrijven zijn betrokken medewerkers te vinden die met hart en ziel hun werk doen. En andersom lopen in kleine organisaties ook mensen rond die ongeïnspireerd en ongemotiveerd hun taken uitvoeren.

Het verschil zit voor mij meer in hoe met vorm wordt omgegaan. Met "vorm" bedoel ik in dit geval het geheel aan systemen, regels, afspraken en procedures waarbinnen je opereert. Is de vorm leidend en volg je die ook als het werkplezier en verbinding in de weg zit? Of is werkplezier en verbinding leidend en gebruik je de vorm om dat te bereiken? Doe je vooral dingen vóór de vorm, of maak je vooral gebruik ván de vorm?

Want waarom registreer je gegevens van een patiënt, leerling, klant of cliënt? Doe je het primair omdat het moet, bijvoorbeeld omdat er sancties volgen als je het niet doet? Of doe je het vooral als manier om inzicht te vergroten en te delen, bijvoorbeeld in de overdracht naar collega’s?

Je doet in beide gevallen hetzelfde (gegevens invoeren in een computer), maar met een heel ander uitgangspunt. Het eerste stelt de vorm voorop en maakt de rest ervan afhankelijk. Het tweede maakt gebruik van de vorm in dienst van iets anders.

Let wel: het ene is niet beter dan het andere. Het gebruiken van de vorm lijkt alleen meer te voelen als spelen – werken op basis van creativiteit, liefde en plezier, gebruikmakend van de middelen die je tot je beschikking hebt.

En dat brengt me terug bij het verschil dat ik zag tussen verloskundige en ziekenhuis. Waar in het ziekenhuis de vorm in de weg stond van de zorg, zag ik bij de verloskundige hoe diezelfde vorm in dienst stond van de zorg.
