= Een duidelijke boodschap

[.lead]
“Je hebt niet in de hand hoe je boodschap landt.” Het zou zomaar een tegeltje aan de wand kunnen zijn.

Laatst hoorde ik dat iemand bij het zien van een video van één van mijn liedjes in huilen was uitgebarsten. (Bij navraag bleek de reden gelukkig niet te zijn dat de persoon in kwestie de muziek afgrijselijk vond, maar dat terzijde.)

Laat dit nu hetzelfde liedje zijn waarop iemand anders reageerde met: “Hee, is dat niet van Acda en De Munnik?”

En een liedje waar ook hardop om gelachen wordt als ik het live speel.

Grappig hoe één en hetzelfde liedje kennelijk zulke diverse reacties kan opleveren.

Had ik bij het schrijven zelf een specifiek boodschap bedacht die het liedje zou moeten overbrengen?

Voor zover ik me kan herinneren niet.

En nu ik het bovenstaande zo op een rij zet is dat eigenlijk dus ook niet echt nuttig. Elke luisteraar ervaart wat ik zing en zeg op een eigen manier, ongeacht wat ik heb bedacht over wat de “juiste” ervaring zou moeten zijn.

Wel zo makkelijk om me daar dan ook niet meer druk over te maken tijdens het schrijven.

En dat geldt natuurlijk niet alleen voor liedjes:

“Wat is je boodschap?”

“Wat wil je precies overbrengen?”

“Wat is het hogere doel hierachter?”

Het lijken nuttige vragen, maar door ze te beantwoorden versterk je de illusie dat je wéét wat de reactie zal zijn als je iets doet.

Het enige wat je kunt doen is iets doen en dan constateren dat er iets gebeurt. Of niet.

En daarna doe je dan weer iets anders. Of niet.

En zo heeft dit stukje toch nog een duidelijke boodschap. Of niet?
