= De nieuwe kleren van de keizer

[.lead]
Vanuit de keuken luisterde ik met een half oor naar het voorlezen uit een sprookjesboek. Bij het sprookje over de nieuwe kleren van de keizer merkte ik dat ik aandachtiger ging luisteren.

In het sprookje houden twee mannen de keizer voor dat zij exclusieve kleren voor hem hebben die alleen intelligente mensen kunnen zien. Omdat de keizer niet dom wil overkomen, doet hij alsof hij de kleren kan zien en koopt hij ze. Ook de hofhouding en de rest van het volk doet mee aan de illusie, totdat bij een optocht een kind opeens roept: “De keizer loopt in z’n blootje!”. Hierdoor stapt plotseling iedereen uit de illusie en staat de keizer in zijn, eh, hemd.

Al luisterend bedacht ik me: is dit niet hoe het hele leven werkt? Als iemand zegt dat we iets moeten doen, bijvoorbeeld een bepaald nieuw dieet volgen dat écht werkt, dan kan het zomaar zijn dat duizenden mensen dit daadwerkelijk gaan doen. Totdat blijkt dat het niet werkt, of dat we erop uitgekeken zijn.

Hetzelfde mechanisme geldt ook voor problemen. Een klimaatprobleem of een vluchtelingenprobleem wordt pas een probleem als genoeg mensen vinden dat het een probleem is. En op een gegeven moment is het probleem weer weg. Het is opgelost of het heeft simpelweg niet meer de aandacht. Of, zoals in het sprookje: het probleem blijkt bij nader inzien een illusionaire mantel te zijn rondom een helemaal prima situatie.

Algemeen gesteld: we doen wel eens mee met een idee. Weten we van tevoren écht of zo’n idee een verbetering is? Nee, dat kunnen we niet weten. Soms blijkt iets goed te werken, soms roept iemand na een tijdje “Dit heeft helemaal geen zin!” en stoppen we er maar mee.

Is dat erg? Welnee! Het is hoe het werkt. Geen enkel idee is heilig, een idee is simpelweg een mogelijkheid om iets te gaan doen. Maar het hoeft niet.

Want om in de metafoor te blijven: of het idee nou een illusionaire mantel is of eentje die je écht kunt dragen, het blijft tijdelijk. Na een paar keer wassen is de nieuwigheid eraf en uiteindelijk gaat hij een keer in de textielbak.

En wat onder de mantel zit? Dat is gelukkig niet zo afhankelijk van de laatste mode.
