= Geboorteplan

[.lead]
Het verloop van een bevalling is niet te voorspellen. En dat is kennelijk ook nergens voor nodig. Maar wácht eens even…

Onlangs was ik bij een groepsbijeenkomst van de verloskundige (hint: ik ben zelf niet zwanger). De stagiaire die erbij was, vertelde dat ze een groep vrouwen had gevraagd naar hun bevallingsverhalen. Ze was benieuwd wat de overeenkomsten en verschillen waren en of er patronen te ontdekken waren. De conclusie: de verhalen waren zó verschillend, dat er geen enkele voorspelling te doen is over hoe een bevalling gaat verlopen.

Fascinerend toch: zo’n belangrijke gebeurtenis in ons leven, waar veel wetenschappelijk onderzoek naar gedaan wordt, en uiteindelijk blijkt dat er van tevoren geen zinnig woord over te zeggen is hoe het gaat verlopen.

Het zette me wel aan het denken. Als de geboorte van een kind komt zoals het komt, en dat gaat al duizenden jaren prima, waarom hechten we op andere gebieden dan zoveel waarde aan voorspellingen over hoe de toekomst zal verlopen? Klimaatverandering, economische groei, hoe een collega reageert als je zegt wat je diep van binnen zou willen zeggen, wat er gebeurt als je kind van vier zelf zijn of haar fruit gaat snijden met een schilmesje – je weet het niet, maar je hebt er wel een voorspelling over.

Misschien is het makkelijker om daar maar eens mee stoppen. Of nee, laat ze lekker komen die voorspellingen, maar zie ze voor wat ze zijn: een gedachte over hoe het zou kunnen zijn, gegeven dat je het in essentie niet weet.
