= Niet de hond

[.lead]
Een langslopende hond kan uiteenlopende reacties oproepen. Wat gebeurt er dan eigenlijk?

Op de camping liep een hond rond. De meeste kinderen waren er dol op. Aaien, ermee spelen. De hond vond dat ook allemaal prima, zo leek het.

Na een paar dagen kwamen er een nieuw gezin kamperen. Hun kinderen bleken doodsbang voor de hond.

Goed, tot zover niks bijzonders. Sommige mensen houden nou eenmaal van honden en andere zijn er bang voor.

Wat me nu alleen opviel, was dat de hond niks deed. Hij blafte niet, beet niet, drong zich niet op. De hond was er en liep rond. Voor de één kennelijk aanleiding om ernaartoe te gaan en hem te aaien, voor de ander om in paniek zo hard mogelijk weg te rennen.

De vraag kwam op: als die hond helemaal niks doet, wat is het dan waar je enthousiast van wordt of juist bang voor bent?

Dan is het is niet de hond, maar het _idee_ dat opkomt bij het zien van de hond. Bij de één is dat kennelijk een angstige gedachte, bij de ander misschien een leuke herinnering.

En dat werkt niet alleen bij honden zo.

Pleinvrees? Het is niet het plein, maar gedachten over wat zou kunnen gebeuren als je op het plein staat (er komt iemand op je afrennen, je weet niet meer waar je vandaan komt, het wordt opeens heel druk).

Liftfobie? Het is niet de lift, maar gedachten over wat zou kunnen gebeuren als je in de lift staat (hij valt stil, hij valt naar beneden, er is geen zuurstof meer, etc.).

Faalangst? Het is niet het falen zelf, maar ideeën die opkomen over wat gaat gebeuren als je iets doet en het gaat niet zoals het moet (en er is dus ook een vastomlijnd idee over "hoe het moet"!).

Kennelijk zijn we als mensen in staat om in een flits een voorspelling te doen over een hele reeks dingen die als dominostenen achter elkaar gaan omvallen als een bepaalde gebeurtenis plaatsvindt. Maar dat we dat bedenken, maakt dat het waar? Weten we dat dan echt zeker?

Het lijkt in ieder geval verdomd echt.

Want wat blijkt: elke keer als ik op die manier de toekomst ga voorspellen, ga ik daarna niet meer doen wat ik eigenlijk van plan was.

Dus vanaf nu ga ik toekomstvoorspellingen angstvallig vermijden.
