= No problemo manifesto

[%hardbreaks]
You think there is a problem.
You tell the person next to you about the problem.
You ask: do you agree there is a problem?
Now two people think there is a problem.

[%hardbreaks]
You see a situation.
You tell the person next to you about the situation.
You ask: any ideas?
Now two people are thinking creatively.

[%hardbreaks]
We are all sensing the world around us.
We see and hear lots of things all day long.
And we think about what those things mean.
And we feel something with those thoughts.
That is how we shape our reality.

Our individual realities.

[%hardbreaks]
There is no such thing as a shared reality.
You may _think_ there is one outside world.
Stop looking for it, you will not find it.

[%hardbreaks]
There is life.
There is energy.
We all live.
We all move.
There is no contradiction in life itself.
There are no problems in life itself.
It just happens.

[%hardbreaks]
Ride the waves.
Be the waves.
Do the Mexican wave.
Wave this nonsense away.
Whatever you do or say -- it’s ok.

[%hardbreaks]
Claro.
No problemo.
Manifesto finito.
