= Getting the gist

[.lead]
Plans, objectives, ideas, targets, processes, procedures: just a couple of the vast amount of concepts encountered in day to day working life. How to get the gist of all that?

Plans change, as do objectives, ideas, targets, processes and procedures. One can get all excited about a plan, or mad as hell about a ridiculous target. Either way – over time, I’m afraid, it is fuzz about something that will one day no longer be there.

Or put differently: everything is always changing.

Ok. So what now? Sit in a corner staring into nothingness, waiting for it all to end?

Well, you _could_ do that. Nothing keeps you from doing it, if that is what you truly feel like doing.

But if everything is always changing, then by definition, so must we. Sitting still in a corner suddenly feels a bit forced then. There you are – consciously holding back any natural movement that may happen.

Let’s play around a bit instead.

If everything is always changing anyway, why not create a new plan? Or change an existing one if you feel like it? Invent a new process? Ignore an existing one? Try out something new while feeling scared shitless? Say that thing that feels right, even if there’s a little voice telling you it may not come our right?

This somehow feels like quite an interesting idea.

For now, that is.
