= Boemerang

[.lead]
Iemand anders zegt iets wat je helemaal niet tof vindt. En boem! Je ontploft. De boemerang is geworpen.

Een tijd terug gingen we (echtgenote, twee kinderen en ik) met de auto naar huis na familiebezoek.

Dochter had tijdens het bezoek een cadeautje gekregen. We hadden haar voor vertrek nog gevraagd: weet je zeker dat je alles hebt? Je knuffels? Je cadeautjes? Ja, was het antwoord. Tot ze na een kilometer rijden ontdekte dat ze haar cadeautje vergeten was.

Echtgenote en ik waren moe en hadden geen zin om terug te gaan, dus we zeiden dat we daar niet aan gingen beginnen. Dochter wilde écht haar cadeautje terug en zette het op een brullen, overgaand in schreeuwen en oorverdovend krijsen.

“We! Moeten! Terug!! Mijn! Cadeautje!!”

Ik zat achter het stuur en werd he-le-maal gek van de herrie vanaf de achterbank.

“En nou is het genoeg! Nu hou je je kop met dat gekrijs!!”

Voor ik het wist was het er al uit – en hierboven staat een vrij milde versie van wat ik zei.

Gevolg? Stilte.

Gezellig? Niet bepaald.

Mijn aandacht ging al snel naar het verkeer. Ik voelde me verkrampt en onrustig terwijl we de snelweg opreden.

Wat nu? Op zichzelf was het écht een hoop herrie vanaf de achterbank. Dat ik daar iets van zei had ik geen spijt van. Had ik dan helemaal nergens spijt van? Moest dochter het maar nemen zoals het was? Moest zij juist maar eerst sorry tegen mij zeggen, omdat zij was begonnen?

Gedachten, gedachten. Ik kwam er niet uit en liet ze maar gaan. Ook mijn lijf leek langzaam weer wat te kalmeren na de woedeuitbarsting.

Eén gedachte kwam op: waar wil ik nou écht excuses voor maken?

Ik draaide me om naar dochter, legde een hand op haar been, keek haar aan en zei:

“Sorry dat ik zo tegen je schreeuwde.”

Wat een rust.

En wat een mooie boemerangworp.
