= Liefde en verbinding

[.lead]
Handel je vanuit angst en onzekerheid? Of handel je vanuit liefde en verbinding?footnote:[Dit is overigens strikt genomen een schijnbare tegenstelling, want soms is er liefde én onzekerheid én verbinding én angst tegelijkertijd. Maar dat terzijde.]

Laatst had ik een telefoongesprek met een klant. Ik was in de veronderstelling mijn best te hebben gedaan en goed werk te hebben geleverd. De klant gaf echter aan teleurgesteld te zijn.

Ik merkte dat ik probeerde de klant te overtuigen dat ik écht het best mogelijke had gedaan, omdat ik niet wilde dat de teleurstelling er was. Dit bleek geen enkel effect te hebben.

Maar wat probeerde ik hier eigenlijk mee te bereiken?

Pas achteraf besefte ik wat ik probeerde te doen. Ik probeerde mijn eigen onprettige gevoel te bestrijden over de teleurstelling die ik dacht te horen bij de klant. Misschien was ik bang dat de teleurstelling iets over mij zei? Of dat dit een eerste stap richting een mislukt project zou zijn?

Angst en onzekerheid leken onbewust de leidraad te zijn voor wat ik zei. Onbewust, want er was niet echt een duidelijk keuzemoment aan te wijzen waarop ik besloot: en nu ga ik eens even deze teleurstelling wegpoetsen.

De welles-nietes woordenwisseling die volgde, bracht ons niet nader tot elkaar, eerder verder van elkaar af. Van verbinding en begrip was geen sprake, laat staan van liefde.

Inderdaad: liefde. De term “liefde” is wellicht niet zo gebruikelijk in het beschrijven van een klant-leverancier relatie op de werkvloer. Maar ja, waarom eigenlijk niet? Zou er iemand op tegen zijn als we ons werk wél doen basis van liefde? Liefde voor het vak? Liefde voor elkaar? Liefde voor wat allemaal mogelijk is als we elkaar helpen?

Het telefoongesprek met de klant was overigens nog niet klaar. Nadat ik me een tijdje had proberen te verdedigen, zei ik: weet je, ik doe heel erg mijn best, maar ik weet niet of we op deze manier tot een werkbare relatie komen.

Iets leek toen te veranderen. Ik zeg zeker niet dat alle problemen toen als sneeuw voor de zon verdwenen. Maar we leken in ieder geval samen te beseffen dat we allebei niet wisten hoe nu verder.

Is dat liefde? Is dat verbinding? Al weet ik dat niet zeker, het voelde wel meteen al een stuk beter.
