= Voorbeeldgedrag

[.lead]
Het goede voorbeeld geven, een voorbeeld zijn, goed voorbeeld doet goed volgen. Maar ook: foute vrienden hebben, op het verkeerde spoor gezet worden en in een negatief klimaat terechtkomen. Er is een hele serie uitdrukkingen over hoe voorbeeldgedrag van invloed kan zijn op… ja, waarop precies? En hoe ontstaat voorbeeldgedrag?

Laat ik voor de gelegenheid eens beginnen met een voorbeeld ;)

De aanleiding voor dit stukje is iets wat ik zag bij onze jongste dochter (1 jaar oud). Aan het einde van de middag ligt de huiskamer vaak bezaaid met speelgoed. Meestal ruimen wij (de ouders in kwestie) dan alvast wat op voordat we gaan eten, met wat hulp van oudere broer (6) en zus (8). Sinds een tijdje begint jongste dochter dan als vanzelf ook mee te helpen: blokken terug in de doos doen, boekjes weer in de kast zetten, kussens weer op de bank leggen. Ze leert dit kennelijk door het te zien en gaat dan op een gegeven moment als vanzelf meedoen. Er lijkt niet echt een bewuste keuze plaats te vinden. Het gebeurt gewoon, simpelweg omdat het logisch lijkt om ook te gaan doen wat je veel om je heen ziet gebeuren.

Nou kun je zeggen: leuk, maar dat is een kind van 1, dat is zich nog niet zo bewust van het eigen gedrag. Toch zie ik dat ik op mijn leeftijd (37) nog steeds onbewust nadoe wat ik om me heen zie.

Recent voorbeeld: mondkapjes. Afgelopen voorjaar droeg nog bijna niemand een mondkapje in winkels. Het nut werd betwijfeld en in Nederland was er ook geen advies van de overheid om dit te doen. Zelf zag ik het nut ook niet echt en heb ik ook tot eind september nul keer een mondkapje gedragen.

Een paar dagen geleden betrapte ik mezelf erop dat ik inmiddels altijd een mondkapje op zak heb en dit vrijwel automatisch op doe als ik een supermarkt of andere winkel in ga. Zelfs de routine om ze regelmatig in de was te doen zit er al in.

Was dit een bewuste keuze? Niet echt, uiteindelijk. Ik heb thuis wel eens benoemd dat ik opeens bijna iedereen een mondkapje zag dragen in de supermarkt. En op een moment heb ik kennelijk ook mondkapjes aangeschaft. Maar ergens ben ik als vanzelf met de stroom meegegaan.

Nu zijn opruimen en een mondkapje dragen vrij simpele voorbeelden. Maar in essentie geldt dit volgens mij voor al ons gedrag. Als we maar genoeg om ons heen zien dat iets op een bepaalde manier gebeurt, gaan we er vanzelf in mee. Of dat nou is in hoe binnen een familie mensen met (en over!) elkaar praten, hoe collega’s elkaar en elkaars werk beoordelen, hoe kinderen in een klas met elkaar spelen, hoe een arts en een patiënt met elkaar omgaan, of hoe supporters zich gedragen in een voetbalstadion: het gedrag wat je veel en vaak om je heen ziet lijkt al vrij snel het “juiste” gedrag te zijn. (Ik gebruik aanhalingstekens, want er is uiteindelijk niet één juiste manier van je gedragen in een situatie.)

Dat is op zich een leuk verhaal, maar er mist nog wel iets. Want er kunnen niet alleen maar volgers zijn. Iemand moet immers de eerste zijn geweest die gedrag vertoonde dat anderen zijn gaan overnemen.

En daar wordt het ook meteen wat vreemd. Want die eerste persoon vertoonde toen per definitie gedrag dat afweek van wat op dat moment gebruikelijk was. Dus door niet een voorbeeld te volgen, is diegene (al dan niet bedoeld) een voorbeeld geworden voor anderen. Daar zit misschien wel iets in.

Wel even een kanttekening. Ik zeg hiermee niet dat je nooit meer een voorbeeld mag volgen en het altijd maar anders moet doen. Ik bedoel het als een neutrale constatering: in de basis doen we kennelijk vrij automatisch mee met wat we om ons heen zien. En dat is vaak ook gewoon prima.

Ik vind het zelf bijvoorbeeld best prettig dat de meeste mensen op de snelweg ongeveer even hard rijden en netjes de maximumsnelheid aanhouden. Dat af en toe iemand het anders doet en met een noodgang voorbijraast, illustreert meteen ook mooi dat het afwijken van wat de meesten doen zeker niet per se beter is dan meedoen met de rest.

Mijn punt is dus niet dat het een beter is dan het ander. Wat ik wél bedoel, wordt misschien nog het meest duidelijk als je jezelf af en toe eens de volgende vraag stelt: het gedrag wat ik op dit moment vertoon, zou ik het prettig vinden als anderen daar een voorbeeld aan nemen? Of anders gezegd: hoe zou ik het vinden als mensen om mij heen zich ook zouden gedragen zoals ik nu?

Dat klinkt misschien als een opdracht of methode, maar ik bedoel dit niet dogmatisch. Want misschien zet ik je met deze vraag wel op een verkeerd spoor. Aan de andere kant: misschien geef ik ook wel een goed voorbeeld. En trouwens: hoe kwam ik er eigenlijk op om deze vraag te stellen?

_Dit artikel is https://www.linkedin.com/pulse/voorbeeldgedrag-floris-huetink/[ook te vinden op LinkedIn]._
