= Virus

video::369648147[vimeo]

[%hardbreaks]
Er is een virus
Het verspreidt zich door het land
We bestrijden het tezamen
Zij aan zij en hand in hand
Oh nee dat mag niet meer, oh jee
Nou ja, doe dan namasté
En houd minimaal een meter of twee afstand

[%hardbreaks]
Er is een virus
Het verspreidt zich door het land
Via websites, televisie, social media en krant
Het informeert, analyseert
En bekijkt van elke kant
Want wat is hier precies nou aan de hand?

[%hardbreaks]
Er is een virus
Het verspreidt zich door het land
We verspreiden het tezamen
Mond tot mond en hand tot hand
De één schreeuwt geen paniek
En de ander moord en brand
Tot het besef dan langzaam landt:
We zijn hier allemaal beland

[%hardbreaks]
Er is een virus
Het verspreidt zich door het land
Het is ongrijpbaar en toch voelbaar
Als een soort enorme hand
Het is te veel voor op een website
En te groot voor in de krant
Het zet jezelf volledig aan de kant
Als je besmet raakt met zo'n groepsverband

[%hardbreaks]
Er is een virus
Het verspreidt zich door het land
En dat virus heeft geen oordeel
Kiest geen kant

